kind = "web"
previewPath = "/"
title = "Manajemen Inventori Gudang"
version = "1.0.0"
id = "artifacts/gudang"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24430

[services.development]
run = "pnpm --filter @workspace/gudang run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/gudang", "run", "build" ]
publicDir = "artifacts/gudang/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24430"
BASE_PATH = "/"
